global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "sogangcomputerclub-monitor"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "backend"
    scrape_interval: 5s
    static_configs:
      - targets: ["backend:8000"]
    metrics_path: "/metrics"

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]
